### ISSUE TITLE
Sunrise/Sunset calculation does not work with negative elevation argument

### ISSUE THREAD

**Issue by i6mael** [MosheBerman/KosherCocoa#16]
In KCGeoLocation.m, when you add an elevation parameter to the methods from within its code, just to test it, it works fine while elevation is positive. However, once you enter there negative elevation parameter, like we have next to Dead Sea or Sea of Galilee, it returns nullable values for both sunrise and sunset.

**Comment by MosheBerman** [comment]
Thanks for filing. I'll investigate.

**Comment by MosheBerman** [comment]
Can you supply the code you used to reproduce?

**Comment by i6mael** [comment]
BS”D

Just substitute some positive value instead of zero into the following methods from within KCGeoLocation.m for ELEVATION parameter (underlined):
- (id)initWithLatitude:(double)latitude andLongitude:(double)longitude andTimeZone:(NSTimeZone *)timeZone
{
    return [self initWithName:@"Unspecified Location" andLatitude:latitude andLongitude:longitude andElevation:0 andTimeZone:timeZone];
}

- (id)initWithName:(NSString *)name andLatitude:(double)latitude andLongitude:(double)longitude andTimeZone:(NSTimeZone *)timeZone
{
    return [self initWithName:name andLatitude:latitude andLongitude:longitude andElevation:0 andTimeZone:timeZone];
}

Those methods call the following method in your code:
- (id)initWithName:(NSString *)name andLatitude:(double)latitude andLongitude:(double)longitude andElevation:(double)elevation andTimeZone:(NSTimeZone *)timeZone

So if you pass the positive values to it, the return sunrise/sunset values are earlier and later correspondingly, which is expected and right behaviour. But if you pass a negative value, the return sunrise/sunset values are zeros.

Respectfully,
Ishmael Pazniak
iOS developer

**Comment by MosheBerman** [comment]
Are you modifying the KCGeoLocation class instead of creating an instance of it and configuring it?

**Comment by i6mael** [comment]
BS”D

Of course I do create an instance and configure it. But then I was just wondering if the elevation parameter works. So I substitute some values for zero in elevation parameter from within KCGeoLocation method implementation, and it worked correctly for positive values, changing the sunrise/sunset time correspondingly. But when I tried to use some negative values, it keeps returning zeros. Probably you use somewhere NSInteger value instead of NSUInteger?
I can make a Skype conversation and share the screen to show how it happens. Don’t hesitate to ask me ))

Respectfully,
Ishmael Pazniak
iOS developer

**Comment by i6mael** [comment]
After spending some time and investigating NSLogs for outputs, I've found where the problem exactly occurs. It's a method "elevationAdjustmentForElevation:(double)elevation" using acos function in KCSunriseAndSunsetCalculator class. It returns NAN if elevation parameter is negative. Here is how you can trace it. Put NSLog into the following method being called:
- (double)UTCSunriseForDate:(NSDate*)date andZenith:(double)zenith adjustForElevation:(BOOL)adjustForElevation
{
    
    double doubleTime = NAN;
    
    if (adjustForElevation)
    {
        zenith = [self adjustZenith:zenith forElevation:self.geoLocation.altitude];
        NSLog(@"Altitude:%.2f\nZenith:%.f", self.geoLocation.altitude, zenith);
    }
...
Output:
Altitude:-0.23
Zenith:nan (while it has a proper value if altitude is a positive one)

Then you add NSLog for acos function result and uncomment NSLog for elevation in the following method being called from here:
- (double)elevationAdjustmentForElevation:(double)elevation
{
    
    double earthRadius = kEarthRadiusInKilometers;
    
    //double elevationAdjustment = 0.0347 * sqrt(elevation);
    NSLog(@"acos: %.15f", acos(earthRadius/(earthRadius + (elevation / 1000))));
    double elevationAdjustment = toDegrees(acos(earthRadius/(earthRadius + (elevation / 1000))));
    
    NSLog(@"Elevation Adjustment: %.15f", elevationAdjustment);
...
Output:
acos: nan
Elevation Adjustment: nan (while both of them have proper values if altitude is a positive one)

**Comment by i6mael** [comment]
Taking into account the mathematics, spoken above, the fix was easy.
The elevation method inKCSunriseAndSunsetCalculator class should be rewritten as following:
- (double)elevationAdjustmentForElevation:(double)elevation
{
    
    double earthRadius = kEarthRadiusInKilometers;
    
    //double elevationAdjustment = 0.0347 * sqrt(elevation);
    double elevationAdjustment = toDegrees(acos(earthRadius/(earthRadius + (fabs(elevation / 1000)))));
    
    //NSLog(@"Elevation Adjustment: %.15f", elevationAdjustment);
    
    return (elevation > 0) ? elevationAdjustment : -(elevationAdjustment);
}

Here it is. We have now the proper elevation calculation for places below sea level ))

**Comment by MosheBerman** [comment]
Ishmael, KosherCocoa is a port of KosherJava. I contacted the author of KosherJava and he says that almost nobody calculates below sea level. I'm going to ask him if he would comment here and see if he has more insight than I do.

**Comment by i6mael** [comment]
What?? Well, I needed to know now exactly how earlier is a sunset at Ein-Gedi, Dead Sea (which is 427 meters below sea level) and one more place next to Sea of Galilee (which is 213 meters below sea level). Are those holy places used by "almost nobody"??? With all due respect, guys, it gives sometimes about entire minute (later for sunrise and earlier for sunset). So, in my point of view, it's very good to have the most universal formula for calculating sunrise/sunset with correction to altitude, which does not results in exception for below sea level (that is negative) values.

**Comment by MosheBerman** [comment]
The halachic view considers sunrise at sea level. Even if you're on a mountain or in Ein-gedi, the halacha says to calculate at sea level. 
I guess it's valid to wonder if the sunrise and sunset methods themselves should handle negative altitudes, but for our case, it doesn't matter.

**Comment by MosheBerman** [comment]
From Eliyahu Hershfeld of KosherJava.com: I don't have a lot of time now, but the issue is a halachic issue.  Does a negative elevation impact Zmanim. The reason it would is obstructions on the horizon, and that impacts people at elevation as well.  As far as I know, I researched it when I wrote the API.  I will try to dig up some sources. My site is down now so I can't look up my previous elevation posts (if it stays down for a while I will go to the way back machine)

**Comment by MosheBerman** [comment]
The truth is if you're asking for a non-halachic sunrise method, I'll look into the cleanest way to implement that.

**Comment by KosherJava** [comment]
@i6mael please note that my comment to Moshe was that halachically a negative elevation causes an issue due to obstruction of the horizon. If you are in a pit you wouldn't say that the zmanim are impacted due to the inability to see the sun? It has been a long time since I coded the API, but I will try to dig up some sources for this. The coding was intentional. Also note, that while you may be able to generate zmanim with a negative elevation that do seem correct, as far as I know the algorithm was not designed to work with them, so your time may not be accurate at all. This all gets into a much larger discussion of DTM (digital terrain mapping), and if obstructions on the horizon actually impact zmanim calculations.

**Comment by i6mael** [comment]
Guys, if you apply to Halacha, you should know that's a Machloketh actually. There are opinions that the horizon line and the moment when one actually sees the sun is more important than it's at sea level. And so it is important to have those calculations properly, for those who prefer to get strict with second opinion. I guess you have the elevation methods implemented not in vain. And even if so, I saw the applications on Android, which actually let user enter altitude together with longitude and latitude of place, because it is Machloketh. I guess we won't get to the holy sources here, but you can ask your rabbis. In other case I will bring you sources which can prove that.

**Comment by MosheBerman** [comment]
Feel free to provide a pull request.

**Comment by i6mael** [comment]
Can you please merge already???

**Comment by KosherJava** [comment]
The patch for negative elevation is simply wrong.  If the calculation were to work it would assume that you somehow slice part of the globe off and I have yet to see a thing about such a calculation.  What angle do you slice things off? do you assume a smaller earth radius? Do you slice it like a funnel, do you slice off a flat portion of the globe for the calculation? Your chnage does not account for this.  In the Java version I think an exception it thrown if a negative elevation.  Positive elevation assumes that nothing in the globe changes, but you can see farther over the horizon due to the elevation. While the change will appear to give a different time, it will almost certainly give an incorrect time.

**Comment by i6mael** [comment]
I need it for a much larger and deeper DTM (digital terrain mapping) algorithm I'm working on, which will give us sunrise/sunset times according to the second Halacha opinion (rabeinu Yona, Talmud Yerushalmi, Baal haTania and many more). That's it.

**Comment by KosherJava** [comment]
Keep in mind that Almost all posking who do deal with obstructions on the horizon only consider this for Vasikin, and not for other zmanim.So use any such calculations with care.

**Comment by i6mael** [comment]
What about merging?

**Comment by MosheBerman** [comment]
We can't accept a pull request that Eliyahu says is wrong. He knows this stuff a lot better than I do and I have to defer to him. Nothing is stopping you from forking the code and working on your forked copy. That doesn't mean we have to integrate the changes for your specific use case.

**Comment by MosheBerman** [comment]
That said, I do wonder if we can have a separate branch for those edge cases (special shitot?)

**Comment by KosherJava** [comment]
I assume that you are working with Rabbi Chaim Keller's calculations.

**Comment by i6mael** [comment]
Pull request is not wrong as far as I deal with DTM sunrise/sunset calculating.

**Comment by MosheBerman** [comment]
For your use case in terrain mapping it's not wrong, but for 80% of users it is. We need to add the improvement in such a way that it works for everyone. We can't accept the PR as is, but there are a few options that might work:

1. Implement a brand new calculator class which adopts the [`KCAstronomicalCalculator`](https://github.com/MosheBerman/KosherCocoa/blob/master/KosherCocoa/Library/Core/Solar/KCAstronomicalCalculator.h) protocol. That way, a new class, (maybe something like `KCSunriseAndSunsetCalculatorWithNegativeAltitudes`) would work in your situation. You'd also have to tell the `KC*ZmanimCalendar` classes where to find it, but that's some configuration on your side. It's not necessarily ideal, but would work.

2. Subclass `KCSunriseAndSunsetCalculator`. The same pros and cons exist as if you were to implement your own subclass, but you don't have to re-create functionality everywhere. Instead you only override that one calculation that you'd like to change.

3. Add a flag to the original `KCSunriseAndSunsetCalculator` along the lines of `allowsCalculationsAtNegativeAltitudes`, which when enabled would use your version of the calculation, allowing for negatives. This keeps the code in one class, and allows your change with minimal effort. I'm concerned about adding flags because they tend to build up over time and then become a mess of logic to follow when debugging. @KosherJava recommended that it be `false` be default and that the documentation be explicit about the potential effects of enabling such a flag.

4. Perhaps a compromise would be to allow `KC*ZmanimCalendar` to take a class name and then work with one of the first two options. So using the custom calendar would look something like this:

    KCZmanimCalendar *zmanimCalendar = [[KCZmanimCalendar alloc] init];
    zmanimCalendar.calculatorClass = [KCSunriseAndSunsetCalculator class];

    // continue configuring the calendar here...

Let me know what you think the right approach is and why and we can take it from there. Thanks again for taking the time to make a contribution to the KosherCocoa library, it's really kind of you.

**Comment by i6mael** [comment]
>The patch for negative elevation is simply wrong. If the calculation were to work it would assume that
>you somehow slice part of the globe off and I have yet to see a thing about such a calculation. 
>What angle do you slice things off? do you assume a smaller earth radius? Do you slice it like a funnel,
>do you slice off a flat portion of the globe for the calculation? Your chnage does not account for this. In
>the Java version I think an exception it thrown if a negative elevation. Positive elevation assumes that
>nothing in the globe changes, but you can see farther over the horizon due to the elevation. While the
>change will appear to give a different time, it will almost certainly give an incorrect time.

Your questions and answers make a contradiction with a common sense logic actually. 
1. If you assume that all altitude (doesn't matter positive or negative) values do not guarantee the right result due to "obstructions on the horizon, and that impacts people at elevation as well" (you, guys, wrote it), then why do you have an altitude value in KCGeoLocation object initializer???
2. If you assume the positive altitude on its own (as provided in KCGeoLocation object initializer), that is disregarding horizon obstructions might give the correct results, then what difference does the negative altitude make to this anyway incorrect assumption?
3. If you say "in terrain mapping it's not wrong, but for 80% of users it is", YOU ARE TOTALLY WRONG, as far as MISHNA BRURA (BIUR HALACHA, 58) agrees to the second opinion (Rabeinu Yona, Talmud Yerushalmi, Tosaphot, RASHBA and many more) while ONLY RASHI (with all due respect) stands for the first opinion, especially as Halacha for this first opinion is based (BY THE WAY) on NON-JEWISH SAGES opinion (read "ISRAEL AND HAZMANIM" book, Chapter 5).
All that means, guys, you are just not capable of admitting the simple fact: YOU ARE WRONG and lack logical foundations. So my advice to you is:
1. either remove altitude arguments from KCGeoLocation so that not to keep deflecting most people who might use this library, or 
2. call it NON-KOSHER COCOA and NON-KOSHER JAVA, as far as it takes into account only NON-JEWISH SAGES OPINION for Halacha and ABSOLUTELY DISRESPECTS SUCH JEWISH SAGES AND LEGACY AS TALMUD YERUSHALMI, RABEINU YONA, TOSAPHOT, RASHBA AND MISHNA BRURA!!!

**Comment by MosheBerman** [comment]
Hey, if you'd like to add support for other opinions in the calculations that's great. I provided a few implementation options that are more flexible in my previous comment.
